# permissions for end users to edit clusterdevfileregistrieslists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clusterdevfileregistrieslist-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devfileregistry-operator
    app.kubernetes.io/part-of: devfileregistry-operator
    app.kubernetes.io/managed-by: kustomize
  name: clusterdevfileregistrieslist-editor-role
rules:
- apiGroups:
  - registry.devfile.io
  resources:
  - clusterdevfileregistrieslists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry.devfile.io
  resources:
  - clusterdevfileregistrieslists/status
  verbs:
  - get
