# permissions for end users to view devfileregistrieslists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devfileregistrieslist-viewer-role
rules:
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistrieslists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistrieslists/status
  verbs:
  - get
