# permissions for end users to view devfileregistrieslists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: devfileregistrieslist-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: devfileregistry-operator
    app.kubernetes.io/part-of: devfileregistry-operator
    app.kubernetes.io/managed-by: kustomize
  name: devfileregistrieslist-viewer-role
rules:
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistrieslists
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registry.devfile.io
  resources:
  - devfileregistrieslists/status
  verbs:
  - get
