# The following patch adds a directive for certmanager to inject CA into the CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    cert-manager.io/inject-ca-from: $(CERTIFICATE_NAMESPACE)/$(CERTIFICATE_NAME)
  name: devfileregistries.registry.devfile.io
spec:
  names:
    kind: DevfileRegistry
    plural: devfileregistries
  group: registry.devfile.io
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
      - description: The URL for the Devfile Registry
        jsonPath: .status.url
        name: URL
        type: string
    name: v1alpha1
    served: true
    storage: true

