# The following patch enables conversion webhook for CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devfileregistries.registry.devfile.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        # this is "\n" used as a placeholder, otherwise it will be rejected by the apiserver for being blank,
        # but we're going to set it later using the cert-manager (or potentially a patch if not using cert-manager)
        caBundle: Cg==
        service:
          namespace: system
          name: webhook-service
          path: /convert
      conversionReviewVersions:
        - v1
  group: registry.devfile.io
  names:
    kind: DevfileRegistry
    plural: devfileregistries
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: The URL for the Devfile Registry
          jsonPath: .status.url
          name: URL
          type: string
      name: v1alpha1
      served: true
      storage: true