//go:build !ignore_autogenerated
// +build !ignore_autogenerated

//
// Copyright (c) 2020-2022 Red Hat, Inc.
// This program and the accompanying materials are made
// available under the terms of the Eclipse Public License 2.0
// which is available at https://www.eclipse.org/legal/epl-2.0/
//
// SPDX-License-Identifier: EPL-2.0
//
// Contributors:
//   Red Hat, Inc. - initial API and implementation

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistry) DeepCopyInto(out *DevfileRegistry) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistry.
func (in *DevfileRegistry) DeepCopy() *DevfileRegistry {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevfileRegistry) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistryList) DeepCopyInto(out *DevfileRegistryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevfileRegistry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistryList.
func (in *DevfileRegistryList) DeepCopy() *DevfileRegistryList {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevfileRegistryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistrySpec) DeepCopyInto(out *DevfileRegistrySpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.TLS.DeepCopyInto(&out.TLS)
	out.K8s = in.K8s
	out.Telemetry = in.Telemetry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistrySpec.
func (in *DevfileRegistrySpec) DeepCopy() *DevfileRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistrySpecK8sOnly) DeepCopyInto(out *DevfileRegistrySpecK8sOnly) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistrySpecK8sOnly.
func (in *DevfileRegistrySpecK8sOnly) DeepCopy() *DevfileRegistrySpecK8sOnly {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistrySpecK8sOnly)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistrySpecStorage) DeepCopyInto(out *DevfileRegistrySpecStorage) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistrySpecStorage.
func (in *DevfileRegistrySpecStorage) DeepCopy() *DevfileRegistrySpecStorage {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistrySpecStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistrySpecTLS) DeepCopyInto(out *DevfileRegistrySpecTLS) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistrySpecTLS.
func (in *DevfileRegistrySpecTLS) DeepCopy() *DevfileRegistrySpecTLS {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistrySpecTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistrySpecTelemetry) DeepCopyInto(out *DevfileRegistrySpecTelemetry) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistrySpecTelemetry.
func (in *DevfileRegistrySpecTelemetry) DeepCopy() *DevfileRegistrySpecTelemetry {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistrySpecTelemetry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevfileRegistryStatus) DeepCopyInto(out *DevfileRegistryStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevfileRegistryStatus.
func (in *DevfileRegistryStatus) DeepCopy() *DevfileRegistryStatus {
	if in == nil {
		return nil
	}
	out := new(DevfileRegistryStatus)
	in.DeepCopyInto(out)
	return out
}
